#!/bin/bash
echo "instalando dependencias..."
sudo apt install w3m && clear

echo "NOMBRE DEL DOCX:"
	read archivo

echo -e "\nMATERIA(ESCRIBE TODO EN MAYÚSCULA):"
	read materia
echo -e "\nTEMA:"
	read tema

echo -e "\nNOMBRE DE ESTUDIANTE:"
	read estudiante

echo -e  "\nNOMBRE DE PROFESOR/A:"
	read profesor

echo -e "\nFECHA DE ENTREGA:"
	read fecha

echo -e "\nAGREGA LINK DE INFORMACION:"
	read link

echo "CREANDO TRABAJO VAGENCY.." && sleep 1s && clear
echo "Listo vago de mierda"

################################################
echo -e "Universidad de Panama\nCentro regional Educativo\nFACULTAD DE INFORMATICA, ELECTRONICA Y COMUNICACION\n\n" >> $archivo.docx
echo -e "Carrera:\nINFORMATICA APLICADA A LA ENSEÑANZA\n\n\n$materia\n\n" >> $archivo.docx
echo -e "Tema\n$tema\n\n" >> $archivo.docx
echo -e "Presentado por:\n$estudiante\n\n" >> $archivo.docx
echo -e "Profesor/a:\n$profesor\n\n" >> $archivo.docx
echo -e "Fecha de entrega\n$fecha\n\n" >> $archivo.docx
echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" >> $archivo.docx

w3m -dump $link >> $archivo.docx

